### ISSUE TITLE
[High packets]

### ISSUE THREAD

**Issue by msmanui** [FrankHeijden/Log4jFix#6]
So im having issues with packets:
https://timings.aikar.co/?id=a2b0d7951b6845d5b37c79076f8d3303#timings
https://spark.lucko.me/RkXYOcP5mN

I made a protocolLib timings and this is the result
[Timings.-.1640038714456.txt](https://github.com/FrankHeijden/Log4jFix/files/7748228/Timings.-.1640038714456.txt)

**Comment by FrankHeijden** [comment]
Hm well, the links you posted don't particularly show Log4jFix as a high consumer of the main thread, in fact, the spark link you posted shows 34ms over a span of 50000ms ~= 0.07% of the main thread. Not sure why the protocollib timings say "Time on main thread", I believe this time is spent in total on the netty threads; but just to be sure, could you run the following command at a busy time?
```
/spark sampler --thread * --interval 1 --timeout 300
```

**Comment by msmanui** [comment]
https://spark.lucko.me/kMwaOrdnrN

**Comment by FrankHeijden** [comment]
Thanks! From the looks of it, Log4jFix has really little impact on your server's performance; most of the time Log4jFix spends on the CPU is by deserialising the json components, a task which has little room for improvement. And even then, the time it spents is ~= 0.19% on the async chat thread.

**Comment by msmanui** [comment]
> ks of it, Log4jFix has really little impact on your server's performance; most of the time Log4jFix spends on the CPU is by deserialising the json components, a task which has little room for improvement. And even then, the time it spents is

Okay and what do u think could be the issue that is lagging

**Comment by FrankHeijden** [comment]
I can't provide Insights on that here, sorry. But I think you're just hitting the limits in general, around 100 players it is expected that performance will be degraded. I am closing this issue ^^
